export interface EditorialItem { slug: string; title: string; category: string; image: string; intro: string; sections: [string, string][]; tags?: string[]; }
const img = (name: string) => '/assets/images/' + name + '.jpg';
export const services: EditorialItem[] = [
  { slug: '01', title: 'Product Engineering', category: 'WHAT WE BUILD', image: img('approach_pavilion'), intro: 'From the first useful prototype to a product people rely on.', sections: [['Start with the user', 'Define the problem, map the experience and validate the smallest useful version before expanding the scope.'], ['Build for the whole journey', 'Design and engineer web applications, mobile experiences and SaaS platforms with accessible interfaces, clear APIs and a maintainable codebase.'], ['Deliver with confidence', 'Bring testing, observability and release planning into the work from the beginning.']] },
  { slug: '02', title: 'AI Engineering', category: 'WHAT WE BUILD', image: img('insight_ai_systems'), intro: 'Intelligence that makes a meaningful difference to everyday work.', sections: [['Connect knowledge', 'Design retrieval systems that ground answers in the right documents and make their sources visible.'], ['Make quality measurable', 'Evaluate accuracy, latency and cost against representative tasks before introducing a system into production.'], ['Keep people in control', 'Give agents clear permissions, useful feedback and human review for consequential actions.']] },
  { slug: '03', title: 'System & Cloud Engineering', category: 'WHAT WE BUILD', image: img('architecture_stack'), intro: 'Reliable foundations for connected products and growing teams.', sections: [['Design the foundation', 'Define service boundaries, data ownership and API contracts around the needs of the product.'], ['Operate reliably', 'Build deployment pipelines, monitoring, backups and recovery procedures into the infrastructure.'], ['Scale deliberately', 'Use measured demand to guide capacity and architectural decisions.']] },
  { slug: '04', title: 'Automation & Integration', category: 'WHAT WE BUILD', image: img('industry_finance'), intro: 'Connect your systems. Give your people room to do more.', sections: [['Map the work', 'Identify repetitive steps, approval points and the systems that hold the source of truth.'], ['Connect safely', 'Build integrations with explicit permissions, traceable events and retry behavior.'], ['Handle the exceptions', 'Surface failed jobs and route unusual cases to the people who can resolve them.']] },
  { slug: '05', title: 'Re-engineering & Modernization', category: 'WHAT WE BUILD', image: img('case_study_monolith'), intro: 'A practical path from unfinished or aging software to dependable systems.', sections: [['Understand what exists', 'Assess the codebase, infrastructure and critical user journeys before choosing a migration strategy.'], ['Improve in stages', 'Refactor the highest-risk areas and replace components incrementally while preserving essential behavior.'], ['Leave a stronger foundation', 'Document decisions and establish tests, delivery workflows and operational visibility.']] },
];
export const industryItems: EditorialItem[] = [
  ['startups', 'Startups & Founders', '4k/startups-4k', 'Turn an ambitious idea into a focused, testable product.', 'Product discovery, MVP development and a technical foundation that can evolve with your business.'],
  ['education', 'Education', '4k/education-4k', 'Make learning more connected, accessible and personal.', 'Learning platforms, knowledge discovery and tools that reduce administrative work for educators.'],
  ['healthcare', 'Healthcare', '4k/healthcare-4k', 'Thoughtful software for people, teams and care workflows.', 'Accessible experiences, careful data access and integrations designed around the needs of care teams.'],
  ['retail', 'Retail & Ecommerce', '4k/retail-4k', 'Bring the customer journey and the operation together.', 'Commerce experiences, inventory integrations and automation across fulfillment and customer support.'],
  ['finance', 'Finance', '4k/finance-4k', 'Build clarity and reliability into complex financial workflows.', 'Data platforms, document processing and auditable workflows with explicit permissions and review.'],
  ['hospitality', 'Hospitality', 'approach_pavilion', 'Create a more connected guest experience.', 'Booking journeys, operational integrations and useful tools for teams across properties.'],
  ['manufacturing', 'Manufacturing', 'case_study_monolith', 'Connect information across the operation.', 'Operational dashboards, system integrations and automation that makes exceptions visible.'],
].map(([slug, title, image, intro, body]) => ({slug, title, image: img(image), intro, category: 'INDUSTRIES', sections: [['Where we can help', body], ['A shared approach', 'Start with the workflow and the people who use it. Validate the solution, engineer a reliable foundation and improve it through real-world feedback.']]}));
export const caseItems: EditorialItem[] = [
 { slug: 'documents-to-intelligence', title: 'From documents to intelligence', category: 'SOLUTION EXAMPLE', image: img('4k/case-4k'), intro: 'A blueprint for turning fragmented knowledge into useful, source-backed answers.', tags: ['RAG', 'FastAPI', 'PostgreSQL', 'AWS'], sections: [['The problem', 'Useful information often sits across documents with different formats and access rules. Finding the right answer can take longer than acting on it.'], ['The architecture', 'Ingest and index documents, preserve access permissions, retrieve relevant passages and show citations alongside generated answers.'], ['What to validate', 'Measure retrieval quality and answer faithfulness with representative questions. This is an illustrative solution, not a published client outcome.']] },
 { slug: 'connected-operations', title: 'From complexity to connected operations', category: 'SOLUTION EXAMPLE', image: img('industry_finance'), intro: 'A blueprint for bringing fragmented workflows into one observable system.', tags: ['APIs', 'Automation', 'Events'], sections: [['The problem', 'Manual handoffs create duplicated work and make failures difficult to trace.'], ['The architecture', 'Connect systems through explicit contracts, durable events and idempotent jobs. Route exceptions to an operator.'], ['What to validate', 'Track completion rates, retry behavior and time spent resolving exceptions. This example describes a possible implementation, not a client result.']] },
 { slug: 'prototype-to-platform', title: 'From prototype to platform', category: 'SOLUTION EXAMPLE', image: img('approach_pavilion'), intro: 'A blueprint for evolving a promising prototype into a dependable product.', tags: ['React', 'Cloud', 'CI/CD'], sections: [['The problem', 'An early prototype may validate a need while leaving reliability, maintainability and operations unresolved.'], ['The architecture', 'Protect critical journeys with tests, establish clear service boundaries and automate delivery.'], ['What to validate', 'Measure reliability and user experience before expanding infrastructure. This is an illustrative engineering scenario.']] },
];
export const articleItems: EditorialItem[] = [
 { slug: 'building-ai-systems', title: 'Building AI systems that create real value', category: 'AI ENGINEERING', image: img('4k/insight_ai-4k'), intro: 'Useful AI starts with a clear problem and a way to tell whether the answer helped.', sections: [['Begin with a task', 'Choose a specific workflow where better information or less repetitive work would make a difference. Define what a useful answer looks like with the people doing the work.'], ['Ground the system', 'Connect the model to relevant information, preserve permissions and show the sources behind the answer. Retrieval is a product decision as much as an infrastructure decision.'], ['Evaluate before expanding', 'Build a representative set of questions and failure cases. Compare quality, latency and cost, then introduce the system gradually with a clear feedback path.']] },
 { slug: 'ai-in-production', title: 'The reality of AI in production', category: 'PERSPECTIVE', image: img('4k/insight_production-4k'), intro: 'A successful demonstration is the beginning of an engineering process.', sections: [['Design for uncertainty', 'Inputs change and model outputs vary. Validate structured responses and provide a useful fallback when the system cannot complete a task reliably.'], ['Make behavior visible', 'Observe requests, retrieval, latency and failures while avoiding unnecessary collection of sensitive content. Give operators enough context to investigate.'], ['Keep releases measurable', 'Version prompts and evaluation sets alongside code. Compare changes against a stable baseline and retain a way to roll back.']] },
 { slug: 'prototype-to-scale', title: 'From prototype to scale', category: 'PRODUCT', image: img('4k/insight_scale-4k'), intro: 'Growth is easier when the next engineering decision follows evidence.', sections: [['Protect the useful core', 'Identify the journeys people rely on and make their behavior explicit through tests and product analytics.'], ['Build the operational foundation', 'Automate releases, monitor errors and rehearse recovery before increasing complexity. Clear ownership matters as much as the technology choice.'], ['Evolve at the right pace', 'Use measured bottlenecks to guide changes. A modular application can take a product a long way before distributed services become necessary.']] },
];
export const architectures: EditorialItem[] = ['Web App', 'SaaS', 'AI', 'RAG', 'Agent', 'Automation', 'Real-Time', 'Enterprise'].map(title => ({slug: title.toLowerCase().replace(/ /g, '-'), title: title + ' architecture', category: 'ARCHITECTURE LAB', image: img('architecture_crystal_stack'), intro: 'Modern architectures. Scalable systems. Real-world solutions.', sections: [['Experience & access', 'Start with the user journey, authentication and permissions. Keep interfaces accessible and service contracts clear.'], ['Application & intelligence', title === 'RAG' || title === 'AI' || title === 'Agent' ? 'Separate retrieval, model execution and tool access. Evaluate outputs and keep a human review path for consequential actions.' : 'Model the core business workflow with explicit boundaries. Use asynchronous jobs for long-running work and define how failures are recovered.'], ['Data & operations', 'Choose storage around access patterns. Add monitoring, automated delivery, backups and cost visibility from the beginning.']]}));
